//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookTaskExtract {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutlookTaskExtract.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated.
        /// </summary>
        internal static string Authenticated {
            get {
                return ResourceManager.GetString("Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        internal static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto discovery could not find Exchange server URL. Enter the URL manually..
        /// </summary>
        internal static string AutoDiscoveryCouldNotFind {
            get {
                return ResourceManager.GetString("AutoDiscoveryCouldNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto discovery failed. Enter the URL manually..
        /// </summary>
        internal static string AutoDiscoveryFailed {
            get {
                return ResourceManager.GetString("AutoDiscoveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking OK will walk you through a the steps of reaching out to Exchange to obtain all tasks of the users you will be supplying..
        /// </summary>
        internal static string ConfirmationMsg {
            get {
                return ResourceManager.GetString("ConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not authenticate.
        /// </summary>
        internal static string CouldNotAuthenticate {
            get {
                return ResourceManager.GetString("CouldNotAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange server found and authenticated..
        /// </summary>
        internal static string ExchangeServerFound {
            get {
                return ResourceManager.GetString("ExchangeServerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not read file from disk. Original Error: {0}.
        /// </summary>
        internal static string FileCouldNotReadUnknown {
            get {
                return ResourceManager.GetString("FileCouldNotReadUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not write files to disk. Access denied. Try saving to a directory that you have write access to..
        /// </summary>
        internal static string FileCouldNotWriteAccessedDenied {
            get {
                return ResourceManager.GetString("FileCouldNotWriteAccessedDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not write files to disk. Original Error: {0}.
        /// </summary>
        internal static string FileCouldNotWriteUnknown {
            get {
                return ResourceManager.GetString("FileCouldNotWriteUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running....
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Auto Discovery....
        /// </summary>
        internal static string RunningAutoDiscovery {
            get {
                return ResourceManager.GetString("RunningAutoDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory to save tasks CSV files for each user..
        /// </summary>
        internal static string SaveCSVToDir {
            get {
                return ResourceManager.GetString("SaveCSVToDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CSV file.
        /// </summary>
        internal static string SelectCSVFile {
            get {
                return ResourceManager.GetString("SelectCSVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the CSV file of users to grab tasks for..
        /// </summary>
        internal static string SelectCSVFileMsg {
            get {
                return ResourceManager.GetString("SelectCSVFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory.
        /// </summary>
        internal static string SelectDirectory {
            get {
                return ResourceManager.GetString("SelectDirectory", resourceCulture);
            }
        }
    }
}
